# sorting numpy array
### In NumPy, sorting an array means arranging its elements in ascending or descending order.

## 1)sorting one D array 

## a)in ascending order




### np.sort()

In [3]:
import numpy as np

org_arr=np.array([20,40,60,10])

new_sorted_arr=np.sort(org_arr) # it will return new sorted array ,doesn't sort original array

print(f"sorting one D array:{new_sorted_arr}") 
print(f"original array:{org_arr}")

sorting one D array:[10 20 40 60]
original array:[20 40 60 10]


### sorting original array

In [ ]:
import numpy as np
np_arr=np.array([10,20,30,40])
np_arr.sort()  # it will sort original array
print(np_arr)

[40 30 20 10]


## conclustion 

### np.sort(arr)  → returns a new sorted array
### arr.sort()    → modifies the original array

### by default it sort in ascending order

# b) in descending order 

### np.sort()

In [ ]:
import numpy as np 
num_arr=np.array([10,20,30,40])
new_sorted_array=np.sort(num_arr)
descending_array=new_sorted_array[::-1]
print(descending_array)


## sorting original array 

In [7]:
import numpy as np 
num_arr=np.array([10,20,30,40])
num_arr.sort()
print(num_arr[::-1])

[40 30 20 10]


# 2) sorting 2-D array 
### while sorting 2-D array we have to use extra parameter axis=0 or axis =1 or axis=none

## 1) Ascending order 

## a) np.sort()

In [ ]:
import numpy as np
num_2darr=np.array([
  [40,-30,40],
  [20,0,60],
  [50,7,9]
])

new_arr=np.sort(num_2darr,)
print("orignal array:",num_2darr)
print("new array:",new_arr)

orignal array: [[ 40 -30  40]
 [ 20   0  60]
 [ 50   7   9]]
new array: [-30   0   7   9  20  40  40  50  60]


### b) original array 

In [ ]:
import numpy as np 
num_2d_arr=np.array(
  [
     [40,-30,40],
     [20,0,60],
     [50,7,9]
  ]
)
num_2d_arr.sort()

print(num_2d_arr)


## b) Descending order 

## 1) np.sort()

In [23]:
import numpy as np 
num_2darr=np.array( [
     [40,-30,40],
     [20,0,60],
     [50,7,9]
  ])
arr=np.sort(num_2darr)[::-1]
print(arr)

[[  7   9  50]
 [  0  20  60]
 [-30  40  40]]


## 2) sorting original array

In [27]:
import numpy as np 
num_2darr=np.array( [
     [40,-30,40],
     [20,0,60],
     [50,7,9]
  ])
num_2darr.sort()
print(num_2d_arr[::-1])

[[  7   9  50]
 [  0  20  60]
 [-30  40  40]]


## understanding axis parameter while sorting a tow diemntinal numpy array

In [ ]:
import numpy as np 
num_2darr=np.array( [
     [40,-30,40],
     [20,0,60],
     [50,7,9]
  ])
arr=np.sort(num_2darr,axis=0)  #axis zero will sort the lement along the column
print(arr)

In [ ]:
import numpy as np 
num_2darr=np.array( [
     [40,-30,40],
     [20,0,60],
     [50,7,9]
  ])
arr=np.sort(num_2darr,axis=1)  #axis 1 will sort the lement along the row
print(arr)

In [ ]:
import numpy as np 
num_2darr=np.array( [
     [40,-30,40],
     [20,0,60],
     [50,7,9]
  ])
arr=np.sort(num_2darr,axis=None)  #axis none will  and then sort it 
print(arr)