## flatten(),reshape,ravel and transpose method 

In [ ]:
import numpy as np
arr=np.arange(1,19,1) # it will create a one dimentinal array with sequence of number

print(arr)
print(arr.shape) # (18,)


# reshape :that means can change the shape of current numpy array 

re_shaped=arr.reshape(3,3,2)  
print("reshaped to (3,3,2)",re_shaped)


# flatten() :convert multi dimentinal array to one dimentinal array

flatten=re_shaped.flatten()
print("flatten the reshaped array:",flatten)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
(18,)
reshaped to (3,3,2) [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]
latten the reshaped array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


## flatten()   vs ravel()




In [ ]:
import numpy as np 
num_arr=np.arange(2,20,1)  # return one deimentinal numpy array
print("original array",num_arr)

# reshape 

reshapped=num_arr.reshape(3,3,2)
print("reshapped(3,3,2):",reshapped)

# flatten

flatten=reshapped.flatten() # it will return the copy of original array after flattern
print("flatten:",flatten)

# ravel

ravel=reshapped.ravel()   # it will return the orignal array after the flatternn 
print("ravel:",ravel)





## transpose 
## def: it will convert row to column or column to row 

In [ ]:
import numpy as np

num_2darr=np.array([
  [10,20,40,60],
  [50,60,40,60],
  [70,20,90,60],
])

print("before transpose:",num_2darr)

transpose_arr=np.transpose(num_2darr)

print("transpose_arr:",transpose_arr)

before transpose: [[10 20 40 60]
 [50 60 40 60]
 [70 20 90 60]]
transpose_arr [[10 50 70]
 [20 60 20]
 [40 40 90]
 [60 60 60]]
