## addition operation 

## addition operation add the corresponding elements

In [ ]:
# example 1:

import numpy as np 
arr=np.array([10,20,8,12])

print(arr+9) 

[19 29 17 21]


In [3]:
#  example 02 

import numpy as np 
arr1=np.array([10,20,8,12])
arr2=np.array([10,20,30,40])

print(arr1+arr2) 

[20 40 38 52]


In [5]:
# example :03
import numpy as np 
arr1=np.array([
  [10,20,8,12],
  [10,20,8,12],
  [10,20,8,12],
  ])
arr2=np.array([
  [10,20,8,12],
  [10,20,8,12],
  [10,20,8,12],
  ])



print(arr1+arr2) 

[[20 40 16 24]
 [20 40 16 24]
 [20 40 16 24]]


# multiplication operation

In [6]:
import numpy as np 
arr1=np.array([10,20,8,12])


print(arr1*5) 

[ 50 100  40  60]


In [ ]:
import numpy as np 
arr1=np.array([10,20,8,12])
arr2=np.array([10,20,8,12])

print(arr1*arr2) 

[1. 1. 1. 1.]


## divistion operation


## dot product of two numpy array